# Generated by Django 5.2.4 on 2025-07-12 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_category', models.CharField(choices=[('page_view', 'Page View'), ('user_interaction', 'User Interaction'), ('conversion', 'Conversion'), ('engagement', 'Engagement'), ('error', 'Error'), ('performance', 'Performance'), ('form_interaction', 'Form Interaction'), ('business_event', 'Business Event')], max_length=50)),
                ('event_label', models.CharField(blank=True, max_length=200, null=True)),
                ('event_value', models.FloatField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('page_url', models.URLField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('custom_parameters', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('daily_visitors', 'Daily Unique Visitors'), ('daily_page_views', 'Daily Page Views'), ('daily_conversions', 'Daily Conversions'), ('daily_revenue', 'Daily Revenue'), ('conversion_rate', 'Conversion Rate'), ('bounce_rate', 'Bounce Rate'), ('avg_session_duration', 'Average Session Duration'), ('popular_pages', 'Popular Pages'), ('traffic_sources', 'Traffic Sources'), ('device_types', 'Device Types')], max_length=50)),
                ('metric_value', models.FloatField()),
                ('metric_data', models.JSONField(blank=True, default=dict)),
                ('date', models.DateField()),
                ('period_type', models.CharField(default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_business_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['metric_type', 'date'], name='analytics_b_metric__9551aa_idx'), models.Index(fields=['date'], name='analytics_b_date_371d73_idx')],
                'unique_together': {('metric_type', 'date', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('appointment_scheduled', 'Appointment Scheduled'), ('dress_inquiry', 'Dress Inquiry'), ('contact_form', 'Contact Form Submission'), ('phone_call', 'Phone Call'), ('email_inquiry', 'Email Inquiry'), ('testimonial_submission', 'Testimonial Submission')], max_length=50)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('medium', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('conversion_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analytics_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='analytics.analyticsevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_conversions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('bounce_rate', models.FloatField(blank=True, null=True)),
                ('engagement_score', models.FloatField(default=0)),
                ('is_converted', models.BooleanField(default=False)),
                ('conversion_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_category', 'timestamp'], name='analytics_e_event_c_372633_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_name', 'timestamp'], name='analytics_e_event_n_bf27e6_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_e_user_id_4d513c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['timestamp'], name='analytics_e_timesta_47536d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['conversion_type', 'timestamp'], name='analytics_c_convers_492e37_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['timestamp'], name='analytics_c_timesta_46dff7_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['start_time'], name='analytics_s_start_t_da4ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='analytics_s_user_id_d3adb7_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_converted'], name='analytics_s_is_conv_a48a94_idx'),
        ),
    ]
