# Generated by Django 5.2.4 on 2025-07-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/additional/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='testimonials.bridetestimonial')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
