# Generated by Django 5.2.4 on 2025-07-10 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dresses/additional/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='store.dress')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
